### ISSUE TITLE
[Compiler error]

### ISSUE THREAD

**Issue by thanhminhmr** [huunghia98/logaspect#2]
> AspectJ Support
> IDEA was unable to find AspectJ compiler .jar among plugin dependencies.
> Please fix <aspectj-maven-plugin> in 'pom.xml' and re-import a project,or set compiler manually via Settings | Compiler | Java Compiler.

Anh compile nó toàn báo lỗi này, và mấy file .aj nó không compile luôn.

**Comment by huunghia98** [comment]
Compile tạo artifact cần ajc ạ. A thêm cái ajc vào compiler của intelij ạ

**Comment by thanhminhmr** [comment]
Thế sau mà xài trên CI/CD thì cái tool này biên dịch một lần thôi chứ, hay
phải biên dịch lại mỗi khi code của target có thay đổi?

Best regards,
Minh

--
*Mai Thanh Minh*
*University of Engineering and Technology, **Vietnam National University*

*144 Xuan Thuy Street, Cau Giay, Ha Noi*
Email: thanhminh.uet@gmail.com / Tel: (+84) 70 21 21 566

**Comment by huunghia98** [comment]
Mình build ra artifact rồi dùng thôi ạ, không cần biên dịch lại. Lúc chạy project thì trong classpath cần thư viện của nó là đc ạ.
